name: Build & Test - Windows

inputs:
  GH_TOKEN:
    required: true
  BOOST_VERSION:
    required: true
  THRIFT_VERSION:
    required: true
  BUILD_TYPE:
    required: true
  SHARED_LIBS_TOGGLE:
    required: true
  OPENSSL_TOGGLE:
    required: true
  ARCH_CHOCO_OPTIONS:
    required: true
  ARCH_ADDRESS_MODEL:
    required: true
  ARCH_CMAKE:
    required: true
  INSTALL_BOOST:
    required: true
  INSTALL_THRIFT:
    required: true
  BOOST_URL:
    required: true
  BOOST_ARCHIVE_NAME:
    required: true
  BOOST_FOLDER_NAME:
    required: true
  BOOST_INCLUDE_FOLDER:
    required: true
  RUN_TESTS:
    required: true
  HAZELCAST_ENTERPRISE_KEY:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  HZ_TEST_AWS_INSTANCE_PRIVATE_IP:
    required: true

runs:
  using: composite
  steps:
    - name: Read Config
      shell: bash
      run: cat .github/config.env >> $GITHUB_ENV

    - name: Download hazelcast-enterprise-tests.jar
      shell: pwsh
      run: |
        gh api "/repos/hazelcast/private-test-artifacts/contents/certs.jar?ref=data" -H "Accept: application/vnd.github.raw" > hazelcast-enterprise-${{ env.HZ_VERSION }}-tests.jar
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Install SysInternals
      shell: pwsh
      run: |
          Invoke-WebRequest `
              "https://download.sysinternals.com/files/SysinternalsSuite.zip" `
              -OutFile "sys-internals.zip" `
              -UserAgent "''"
          Expand-Archive sys-internals.zip -DestinationPath sys-internals

    - name: Build & Install
      env:
        BUILD_DIR: build
        BUILD_CONFIGURATION: ${{ inputs.BUILD_TYPE }}
        BIT_VERSION: ${{ inputs.ARCH_ADDRESS_MODEL }}
        INSTALL: ON
        CXXFLAGS: '/I C:\Thrift\include\'
      shell: pwsh
      run: |
        .\scripts\build-windows.bat `
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}\destination `
            -DBUILD_SHARED_LIBS=${{ inputs.SHARED_LIBS_TOGGLE }} `
            -DWITH_OPENSSL=${{ inputs.OPENSSL_TOGGLE }} `
            -DBUILD_TESTS=ON `
            -DBUILD_EXAMPLES=OFF `
            -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake `
            -DVCPKG_MANIFEST_FEATURES='build-tests'

    - name: Test
      if: ${{ inputs.run_tests }}
      env:
        BUILD_DIR: build
        BUILD_CONFIGURATION: ${{ inputs.BUILD_TYPE }}
        HAZELCAST_ENTERPRISE_KEY: ${{ inputs.HAZELCAST_ENTERPRISE_KEY }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        HZ_TEST_AWS_INSTANCE_PRIVATE_IP: ${{ inputs.HZ_TEST_AWS_INSTANCE_PRIVATE_IP }}
        SSL_CERT_FILE: 'C:\cacert.pem'
      shell: pwsh
      run: |
        $dump = start-process -NoNewWindow sys-internals\procdump.exe {-accepteula -e -ma -w client_test.exe crash.dmp}
        .\scripts\test-windows.bat
        $dump | wait-process

    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: dump-${{ env.JOB_NAME }}
        path: |
          **/*.pdb
          *.dmp
