name: nightly-macOS-x86_64

on:
  workflow_dispatch:
    inputs:
      run_tests:
        type: boolean
        description: Enable/Disable test stage
        default: true
  schedule:
    - cron: '0 0 * * *'

jobs:
  nightly-macOS-x86_64:
    strategy:
      fail-fast: false
      matrix:
        boost:
            - version: 1.71.0
            - version: 1.76.0

        build_type:
          - type: Debug
            warn_as_err: ON
          - type: Release
            warn_as_err: OFF

        shared_libs:
          - toggle: OFF
            name: Static
          - toggle: ON
            name: Shared

        with_openssl:
          - toggle: OFF
            name: 'noSSL'
          - toggle: ON
            name: 'SSL'

    runs-on: macos-latest

    name: >-
      macOS-x86_64
      (${{ matrix.build_type.type }}, ${{ matrix.shared_libs.name }}, ${{ matrix.with_openssl.name }}, ${{matrix.boost.version}})

    env:
      OPENSSL_ROOT_DIR: /usr/local/opt/openssl/

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          brew install openssl@1.1 thrift curl

      - name: Start RC
        run: |
          ./scripts/start-rc.sh